#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
COMMAND="${1:-refresh}"
if [[ $# -gt 0 ]]; then
  shift
fi

OUTPUT_PATH="${E2E_RUNTIME_ENV_FILE:-$ROOT_DIR/docs/internal/.e2e-runtime-env}"
FLY_APP="${E2E_FLY_APP:-prd-to-prod}"
CONSOLE_URL="${E2E_CONSOLE_URL:-https://prd-to-prod.fly.dev}"
WEB_URL="${E2E_WEB_URL:-${E2E_STUDIO_URL:-https://www.prdtoprod.com}}"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --path)
      OUTPUT_PATH="$2"
      shift 2
      ;;
    --app)
      FLY_APP="$2"
      shift 2
      ;;
    --console-url)
      CONSOLE_URL="$2"
      shift 2
      ;;
    --web-url)
      WEB_URL="$2"
      shift 2
      ;;
    *)
      echo "Unknown option: $1" >&2
      exit 1
      ;;
  esac
done

fetch_remote_value() {
  local remote_key="$1"
  local encoded

  encoded=$(
    fly ssh console --app "$FLY_APP" -C \
      "node -e \"process.stdout.write(Buffer.from(process.env['$remote_key']||'').toString('base64'))\"" \
      2>/dev/null | tr -d '\r\n'
  )

  if [[ -z "$encoded" ]]; then
    echo "Missing $remote_key on Fly app $FLY_APP" >&2
    exit 1
  fi

  python3 -c "import sys,base64; sys.stdout.write(base64.b64decode(sys.argv[1]).decode())" "$encoded"
}

write_env_file() {
  local agent_key app_id app_key internal
  agent_key="$(fetch_remote_value OPENAI_API_KEY)"
  app_id="$(fetch_remote_value PIPELINE_APP_ID)"
  app_key="$(fetch_remote_value PIPELINE_APP_PRIVATE_KEY)"
  internal="$(fetch_remote_value BUILD_INTERNAL_SECRET)"

  mkdir -p "$(dirname "$OUTPUT_PATH")"
  umask 077
  {
    printf '# Generated by scripts/e2e/runtime-env.sh on %s\n' "$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
    printf 'export E2E_OPENAI_API_KEY=%q\n' "$agent_key"
    printf 'export PIPELINE_APP_ID=%q\n' "$app_id"
    printf 'export PIPELINE_APP_PRIVATE_KEY=%q\n' "$app_key"
    printf 'export BUILD_INTERNAL_SECRET=%q\n' "$internal"
    printf 'export E2E_CONSOLE_URL=%q\n' "$CONSOLE_URL"
    printf 'export E2E_WEB_URL=%q\n' "$WEB_URL"
  } > "$OUTPUT_PATH"
  chmod 600 "$OUTPUT_PATH"
}

case "$COMMAND" in
  refresh)
    write_env_file
    echo "Saved E2E runtime env to $OUTPUT_PATH"
    ;;
  print)
    if [[ ! -f "$OUTPUT_PATH" ]]; then
      echo "Runtime env file not found: $OUTPUT_PATH" >&2
      exit 1
    fi
    cat "$OUTPUT_PATH"
    ;;
  *)
    echo "Usage:" >&2
    echo "  scripts/e2e/runtime-env.sh refresh [--path <env-file>] [--app <fly-app>]" >&2
    echo "  scripts/e2e/runtime-env.sh print [--path <env-file>]" >&2
    exit 1
    ;;
esac
